# Configuration file for vision model fine-tuning

# Model parameters
model_name: "unsloth/Llama-3.2-11B-Vision-Instruct"
load_in_4bit: true
use_gradient_checkpointing: "unsloth"
name_trained_model: "VizSage_final_model"

# Model fine-tuning settings
finetune_vision_layers: false
finetune_language_layers: true
finetune_attention_modules: true
finetune_mlp_modules: true
finetune_norm_layers: false

# LoRA parameters
lora_r: 32
lora_alpha: 32
lora_dropout: 0.05
lora_bias: "none"
use_rslora: true
random_state: 3407

# Training parameters
batch_size: 2
grad_accum: 8
warmup_steps: 250
epochs: 4
lr: 0.0002
weight_decay: 0.02
logging_steps: 5
optim: "adamw_8bit"
scheduler: "cosine"
seed: 0
eval_steps: 100
max_grad_norm: 1.0

# early stopping parameters
use_early_stopping: true
early_stopping_patience_ratio: 1
early_stopping_threshold: 0.001
early_stopping_metric: "eval_loss"
early_stopping_greater_is_better: false

# Inference parameters
instruction: "You are an expert art historian. Answer the questions you will be asked about the image."

# Hardware options
use_bf16: true

# Dataset parameters
dataset: "AQUA"
base_path: "data"
external_knowledge: true
external_knowledge_path: "data/semart.csv"
num_proc: 4
max_seq_length: 2048

# Weights & Biases logging
use_wandb: true
wandb_project: "VizSage"
wandb_tags: ["llama3", "vision", "finetune"]

# Output settings
output_dir: "outputs"

# Streaming parameters
use_streaming: true
stream_buffer_size: 1000
save_steps: 100
n_saves: 5
test_samples_to_check: 1