# Configuration file for vision model fine-tuning

# Model parameters
model_name: "unsloth/Llama-3.2-11B-Vision-Instruct"
load_in_4bit: true
use_gradient_checkpointing: "unsloth"
name_trained_model: "VizSage_final_model"

# Model fine-tuning settings
finetune_vision_layers: false
finetune_language_layers: true
finetune_attention_modules: true
finetune_mlp_modules: true
finetune_norm_layers: false

# LoRA parameters
lora_r: 32
lora_alpha: 32
lora_dropout: 0.05
bias: "none"
use_rslora: true


# Training parameters
batch_size: 2
grad_accum: 8
warmup_steps: 250
epochs: 4
lr: 0.0002
weight_decay: 0.02
logging_steps: 1
optim: "adamw_8bit"
scheduler: "cosine"
seed: 3407
eval_steps: 100
max_grad_norm: 1.0
use_text_normalization: false
debug_exact_match: true

# Early stopping parameters
use_early_stopping: false
early_stopping_patience_ratio: 0.1
early_stopping_threshold: 0.01


# Inference parameters
instruction: "You are an expert art historian. Answer the questions you will be asked about the image."

max_new_tokens: 128
temperature: 0.1
top_p: 0.95
top_k: 50
num_beams: 1
do_sample: true

# Hardware options
use_bf16: true

# Dataset parameters
dataset: "AQUA"
base_path: "data"
external_knowledge: true
external_knowledge_path: "data/semart.csv"
num_proc: 4
max_seq_length: 2048

reproducible: false  # true = use fixed seed, false = random each run

# Weights & Biases logging
use_wandb: true
wandb_project: "VizSage"
wandb_tags: ["llama3", "vision", "finetune"]

# Output settings
output_dir: "outputs"

save_model: true  # Set to true if you want to save an additional copy
save_path: "models/trained_model"  # Path for additional save

# Streaming parameters
use_streaming: true
use_val_streaming: false
stream_buffer_size: 1000
save_steps: 100
n_saves: 5
